### ISSUE TITLE
What reason removed --project-root option?

### ISSUE THREAD

**Issue by granoeste** [f3ath/cider#22]
What reason removed --project-root option at latest release  0.1.0 ?

```
$ cider version --project-root app

Unhandled exception:
Could not find an option named "project-root".
Usage: cider version [arguments]
-h, --help    Print this usage information.
```

**Comment by f3ath** [comment]
`--project-root` was not an intentional feature, it was rather a side-effect to enable testing. At v0.1 Cider detects project root automatically by locating `pubspec.yaml` starting from the current folder and going up the tree. So you can run it either from the project root of from any subdirectory. Do you feel you still need that argument? What is your usecase?

**Comment by granoeste** [comment]
I bump up version code and number with cider on CI Build.
Our product has separated module under project directory. application, models, data, etc.
So I had to define application directory with --project-root.

Currently, I change the directory before running the command.

**Comment by f3ath** [comment]
Reintroduced `-project-root` in v0.2.
